project 'FakeNews.xcodeproj/'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FakeNews' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google/SignIn'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'FakeNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
